name: 'CACE'
description: 'Composite action to run a CACE design'

inputs:
  pdk_family:
    description: 'PDK family supported by volare, such as sky130'
    required: false
    default: 'sky130'
  open_pdks_rev:
    description: 'PDK hash for volare'
    required: false
    default: '4d5af10bfee4dab799566aaf903bb22aee69bac9'
  cace_rev:
    description: 'CACE commit hash'
    required: false
    default: '7fb380179a9b786f489375270931c3593e620e86'
  cace_root:
    description: 'working directory'
    required: false
    default: '.'
  cace_datasheet:
    description: 'path to the datasheet relative to cace_root'
    required: false
    default: ''
  cace_source:
    description: 'source for the netlist [schematic, layout, rcx, all, best]'
    required: false
    default: 'best'
  cace_args:
    description: 'additional arguments for CACE'
    required: false
    default: ''
  token:
    description: 'Github PAT'
    required: true
runs:
  using: "composite"
  steps:
    # Enable the PDK
    - name: Install volare
      shell: bash
      run: |
        python3 -m pip install volare
    - name: Cache ${{ inputs.pdk_family }} PDK
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.volare-${{ inputs.pdk_family }}
        key: cache-${{ inputs.pdk_family }}-pdk-${{ inputs.open_pdks_rev }}
    - name: Enable ${{ inputs.pdk_family }} PDK
      shell: bash
      run: |
        volare enable --pdk ${{ inputs.pdk_family }} --pdk-root ${{ github.workspace }}/.volare-${{ inputs.pdk_family }} ${{ inputs.open_pdks_rev }}
        echo "PDK_ROOT=${{ github.workspace }}/.volare-${{ inputs.pdk_family }}" >> $GITHUB_ENV
    # Install Nix
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ inputs.token }}
    # Setup the binary cache
    - name: Setup cache
      uses: cachix/cachix-action@v14
      with:
        name: openlane
        extraPullNames: openlane
    # Run CACE
    - name: Run CACE
      uses: workflow/nix-shell-action@v3.3.2
      with:
        flakes: github:efabless/cace/${{ inputs.cace_rev }}
        script: |
          # Run CACE inside CACE_ROOT
          cd ${{ github.workspace }}
          cd ${{ inputs.cace_root }}
          cace ${{ inputs.cace_datasheet }} --source ${{ inputs.cace_source }} ${{ inputs.cace_args }}
